export const USAddressFormatCountries = [
  "United States",
  "Canada",
  "Mexico",
  "United Kingdom",
  "Australia",
  "Ireland",
  "New Zealand",
  "South Africa",
  "Philippines",
  "India",
  "Israel",
];

export const COUNTRIES_REQUIRING_STATE = [
  "US", // United States
  "CA", // Canada
  "AU", // Australia
  "MX", // Mexico
  "BR", // Brazil
  "IN", // India
  "NG", // Nigeria
];

export const EU_COUNTRIES = [
  "AT",
  "BE",
  "BG",
  "HR",
  "CY",
  "CZ",
  "DK",
  "EE",
  "FI",
  "FR",
  "DE",
  "GR",
  "HU",
  "IT",
  "LV",
  "LT",
  "LU",
  "MT",
  "NL",
  "PL",
  "PT",
  "RO",
  "SK",
  "SI",
  "ES",
  "SE",
];

export const EuropeanEUCountries = [
  "Austria",
  "Belgium",
  "Bulgaria",
  "Croatia",
  "Cyprus",
  "Czechia",
  "Denmark",
  "Estonia",
  "Finland",
  "France",
  "Germany",
  "Greece",
  "Hungary",
  "Italy",
  "Latvia",
  "Lithuania",
  "Luxembourg",
  "Malta",
  "Netherlands",
  "Poland",
  "Portugal",
  "Romania",
  "Slovakia",
  "Slovenia",
  "Spain",
  "Sweden",
];

export const EuropeanNonEUCountries = [
  "Åland Islands",
  "Albania",
  "Andorra",
  "Belarus",
  "Bosnia and Herzegovina",
  "Faroe Islands",
  "Gibraltar",
  "Guernsey",
  "Iceland",
  "Ireland",
  "Isle of Man",
  "Jersey",
  "Kosovo",
  "Liechtenstein",
  "Moldova",
  "Monaco",
  "Montenegro",
  "North Macedonia",
  "Norway",
  "Russia",
  "San Marino",
  "Serbia",
  "Svalbard and Jan Mayen",
  "Switzerland",
  "Ukraine",
  "United Kingdom",
  "Vatican City",
];

export const EuropeanCountries = [
  ...EuropeanEUCountries,
  ...EuropeanNonEUCountries,
];

export const continentOrder = [
  "North America",
  "Europe",
  "Caribbean",
  "Central America",
  "South America",
  "Asia",
  "Oceania",
  "Africa",
];

export const select_continents = [
  { label: "Asia", value: "Asia" },
  { label: "Europe", value: "Europe" },
  { label: "North America", value: "North America" },
  { label: "Caribbean", value: "Caribbean" },
  { label: "Central America", value: "Central America" },
  { label: "Oceania", value: "Oceania" },
  { label: "South America", value: "South America" },
  { label: "Africa", value: "Africa" },
];

export const usRegions = {
  Midwest: [
    "IL",
    "IN",
    "IA",
    "KS",
    "MI",
    "MN",
    "MO",
    "NE",
    "ND",
    "OH",
    "SD",
    "WI",
  ],
  South: [
    "AL",
    "AR",
    "FL",
    "GA",
    "KY",
    "LA",
    "MS",
    "NC",
    "OK",
    "SC",
    "TN",
    "TX",
    "VA",
    "WV",
  ],
  Northeast: ["CT", "DE", "ME", "MD", "MA", "NH", "NJ", "NY", "PA", "RI", "VT"],
  West: [
    "AK",
    "AZ",
    "CA",
    "CO",
    "HI",
    "ID",
    "MT",
    "NV",
    "NM",
    "OR",
    "UT",
    "WA",
    "WY",
  ],
};
