export const defaultOrg = {
  name: "",
  logo: "",
  location: {
    full: "",
    locale: "",
    city: "",
    state: "",
    stateAbbr: "",
    region: "",
    country: "",
    countryAbbr: "",
    continent: "",
    coordinates: {
      latitude: 0,
      longitude: 0,
    },
    currency: {
      code: "",
      name: "",
      symbol: "",
      format: "",
    },
    demonym: "",
    timezone: "",
    timezoneOffset: 0,
  },
  about: "",
  contact: {
    organizer: "",
    organizerTitle: "",
    primaryContact: "",
  },
  links: {
    website: "",
    instagram: "",
    facebook: "",
    threads: "",
    vk: "",
    phone: "",
    phoneExt: "",
    address: "",
    linkAggregate: "",
    linkedIn: "",
    youTube: "",
    other: "",
  },
  isComplete: false,
};
